services:
  bal-kit-test:
    build:
      context: .
      dockerfile: Dockerfile.testing
    container_name: bal-kit-testing
    volumes:
      # Mount source code (read-only to protect local files)
      - .:/var/www/bal-kit:ro
      # Mount Composer cache for faster dependency installation
      - bal-kit-composer-cache:/home/balkit/.composer
    environment:
      - COMPOSER_CACHE_DIR=/home/balkit/.composer/cache
      - BAL_KIT_VERSION=${BAL_KIT_VERSION:-^1.5.0}
      - TEST_MODE=${TEST_MODE:-all}
    working_dir: /var/www/bal-kit
    # Use tmpfs for test workspace (fast and isolated)
    tmpfs:
      - /tmp/bal-kit-test-workspace:rw,noexec,nosuid,size=1g
    command: ["./scripts/docker/docker-test.sh", "${TEST_COMMAND:-all}"]

volumes:
  bal-kit-composer-cache:
    driver: local
