name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    name: Integration Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Create Laravel Application
        run: |
          composer create-project laravel/laravel test-app --prefer-dist --no-interaction
          cd test-app

      - name: Install BAL Kit
        run: |
          cd test-app
          composer config repositories.local path ../
          composer require get-tony/bal-kit:@dev --no-interaction

      - name: Test BAL Kit Installation
        run: |
          cd test-app
          php artisan bal:install --preset=full --no-interaction
          php artisan bal:publish --list

      - name: Test Frontend Build
        run: |
          cd test-app
          npm install
          npm run build

      - name: Test Application
        run: |
          cd test-app
          php artisan serve --host=127.0.0.1 --port=8000 &
          sleep 5
          curl -f http://127.0.0.1:8000 || exit 1
